name: flashfold
channels:
  - conda-forge 
  - bioconda
  - biocore
  - defaults
dependencies:
  - git
  - python=3.10
  - openmm==7.7.0 
  - pdbfixer
  - kalign2=2.04 
  - hhsuite=3.3.0
  - mmseqs2=15.6f452
  - perl
  - ncbi-datasets-cli
  - hmmer
  - pip
  - pip:
      - colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold
      - jax[cuda]>=0.3.8,<0.4