[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flashfold"
version = "1.0.0"
description = "A tool for protein and protein complex structure prediction."
authors = [
    { name = "Chayan Kumar Saha", email = "chayan_saha@outlook.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Linux",
    "Operating System :: MacOS",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Development Status :: 4 - Beta",
]
[project.scripts]
flashfold = "flashfold.main:main"

[tool.setuptools]
packages = ["find:"]

[tool.setuptools.cmdclass]
install = "setup.CustomInstallCommand"