name: flashfold
channels:
  - conda-forge 
  - bioconda
  - biocore
  - defaults
dependencies:
  - python=3.10
  - openmm==7.7.0 
  - pdbfixer
  - ncbi-datasets-cli
  - hmmer
  - pip
  - pip:
      - colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold
      - colabfold[alphafold]
      - jax[cuda12]==0.4.28
      - tensorflow
      - silence_tensorflow
      - setuptools~=69.0.3
      - pyinstaller
      - poetry
      - pytest
      - wget~=3.2
      - ujson~=5.10.0
      - numpy~=1.26.4
      - requests~=2.32.3
      - tqdm~=4.66.5
      - py3Dmol
