name: flashfold
channels:
  - conda-forge 
  - bioconda
  - biocore
  - defaults
dependencies:
  - git
  - python=3.10
  - openmm==8.0.0
  - pdbfixer==1.9
  - perl
  - ncbi-datasets-cli
  - pip
  - pip:
      - colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold
      - jax==0.4.23
      - jaxlib==0.4.23
      - colabfold[alphafold]
      - silence_tensorflow
      - setuptools~=69.0.3
      - wget~=3.2
      - ujson~=5.10.0
      - numpy~=1.26.4
      - requests~=2.32.3
      - tqdm~=4.66.5
conda create -p "$COLABFOLDDIR/colabfold-conda" -c conda-forge -c bioconda \
    git python=3.10 openmm==8.0.0 pdbfixer==1.9 \
     -y
conda activate "$COLABFOLDDIR/colabfold-conda"

# install colabfold
"$COLABFOLDDIR/colabfold-conda/bin/pip" install --no-warn-conflicts \
    "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"
"$COLABFOLDDIR/colabfold-conda/bin/pip" install jax==0.4.23 jaxlib==0.4.23
"$COLABFOLDDIR/colabfold-conda/bin/pip" install "colabfold[alphafold]"
"$COLABFOLDDIR/colabfold-conda/bin/pip" install silence_tensorflow