name: flashfold
channels:
  - conda-forge 
  - bioconda
  - biocore
  - defaults
dependencies:
  - python=3.10
  - openmm==8.0.0
  - pdbfixer==1.9
  - perl
  - ncbi-datasets-cli
  - hmmer
  - pip
  - pip:
      - colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold
      - jax==0.4.23
      - jaxlib==0.4.23
      - colabfold[alphafold]
      - silence_tensorflow
      - setuptools~=69.0.3
      - poetry
      - pytest
      - pyinstaller
      - wget~=3.2
      - ujson~=5.10.0
      - numpy~=1.26.4
      - requests~=2.32.3
      - tqdm~=4.66.5
