name: Linux Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        conda env update -f envs/linux-environment.yml
    - name: Run tests
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate flashfold
        pytest -k "not test_fold_batch"
