name: Mac OS Python Package using Conda

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install conda
      run: |
        wget -q -P . https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
        bash ./Miniforge3-MacOSX-arm64.sh -b -u -p ./miniforge3
        rm ./Miniforge3-MacOSX-arm64.sh
    - name: Install dependencies with brew
      run: |
        brew install wget
        brew install brewsci/bio/hh-suite
        brew install kalign
        brew install mmseqs2
        brew install hmmer
    - name: Install dependencies
      run: |
        conda env update -f envs/mac-environment.yml
    - name: Test
      run: |
        $(conda info --base)/envs/flashfold/bin/colabfold_batch -h
        echo "Installation completed."
