name: Mac OS Python Package using Conda

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies with brew
      run: |
        brew install wget
        brew install brewsci/bio/hh-suite
        brew install kalign
        brew install mmseqs2
        brew install hmmer
    - name: Install dependencies
        conda env update -f envs/mac-environment.yml
    - name: Test
      run: |
        $(conda info --base)/envs/flashfold/bin/colabfold_batch -h
        echo "Installation completed."
