name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Test with pip
      run: |
        conda env update -f envs/linux-environment.yml
        conda activate flashfold
        pip install .
        python -c "import flashfold; print('FlashFold installed successfully!')"
